### PR TITLE
removed dependencies from slf4j

### PR DESCRIPTION
**Pull request by jluthiger**
I am testing the SGr libs for an integration into a Spring Boot project - later maybe useful for our TestLab at the FHNW. I found an incompatibility between the slf4j libs, on which the SGr drives depend, and the Spring Ecosystem.

### CODE REVIEW

**Comment by jluthiger** [comment]
The spring boot project failed during bootstrap with an exception of "log4j-slf4j-impl cannot be present with log4j-to-slf4j".

**Comment by ergo-furrer** [comment]
@jluthiger Did you also try to load the commhandler4modbus library, since the library uses slf4j too. If yes, did this work together with Spring?

**Comment by jluthiger** [comment]
@ergo-furrer : Yes, but with this library I was able to exclude the dependency. See snippet from `build.gradle` below:

```text
implementation group: 'ch.smartgridready', name: 'sgr-driver-api', version: '1.0.0'  
implementation (group: 'ch.smartgridready', name: 'commhandler4modbus', version: '1.0.0') {
	// exclude easymodbus library with its 'slf4j' dependency,
	// which leads to a conflict with the spring-framework  
	exclude module: 'easymodbus'
	exclude group: 'SGrJava.InterfaceFactory', module: 'emfEI4Modbus'	
}
```
The same approach did not work for `easymodbus`.

**Comment by ergo-furrer** [comment]
@jluthiger OK i see.

You also had to change the logger of the ModbusCallHandler from `log4j2 `to `java.utils.Logging` for the 'implementation' dependencies. I am wondering why this had to be done. Seems that you had a conflict with Spring too (not related to slf4j).
I am also wondering what dependency includes the `log4j-to-slf4j`.

I think we should invest some time to find out which logging framework is the most suitable for our libraries. Intuitively I would propose `slf4j` since it provides a facade for many common logging frameworks. However that lead to some problems with your Spring Boot setup. What is your opinion regarding the right framework to be used for SGrJava projects? 

According to my knowledge Spring boot applications can be configured to run with slf4j and you might consider using slf4j for your application as well.

I apologise to bother you with all this questions, however we spent not many thoughts about the logging framework to be used in our projects until now. Maybe it's time to do it now....

**Comment by jluthiger** [comment]
I know now better, what was the reason to raise the following exception 

``` shell

Caused by: org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
```

This error message is a little misleading. I found out that Spring Boot 3.2.0 depends on slf4j-api v2.x.x, while the `jssc` package uses slf4j-api v1.7.6. The logger-backends used by spring, addresses v2 of the slf4j-api. Therefore version 1 contradicts the spring setup, see [The new features of SLF4J 2.x](https://andbin.dev/java/new-features-slf4j-2x).

To test this, I modified the `build.gradle` as follows:

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'io.github.java-native:jssc:2.9.6'
    implementation 'org.slf4j:slf4j-api:2.0.9'
}
```

This is working!

`slf4j` as a wrapper for logging frameworks within a library is a good choice - and the right way to go. However, attention must be paid to which versions are pulled into the library due to the dependencies.

**Comment by ergo-furrer** [comment]
Thanks for your investigation!

If I understand correctly you are able to use the EasyModbus driver code as is now, without modification. We just need to modify the build.gradle file as you mention above.

Would you mind if I modify the logger to slf4j for the EasyModus implementation on this branch and give it back to you for review?

**Comment by ergo-furrer** [comment]
@jluthiger 
I changed EasyModbus to use slf4j V2. Please could you have a look at the changes.
Thanks a lot!

**Comment by eaf-fhnw** [comment]
@ergo-furrer I checked your changes. I had to update build.gradle so only the tests depend on log4j and its slf4j wrapper. I'm now able to include this library successfully into a spring boot application. it's dependencies concerning the SGr-libs are as follows:

```groovy
implementation group: 'ch.smartgridready', name: 'sgr-driver-api', version: '1.0.0'  
implementation (group: 'ch.smartgridready', name: 'commhandler4modbus', version: '1.0.0') {
		// exclude easymodbus library with its 'slf4j' dependency,
		// which leads to a conflict with the spring-framework  
		exclude module: 'easymodbus'
}
// inject easymodbus library v1.0.1
implementation fileTree(dir: "libs", include: ["*.jar"])
```

**Comment by ergo-furrer** [comment]
> ```groovy
> implementation fileTree(dir: "libs", include: ["*.jar"])
> ```

Hmm, nice to hear, that you got the library working. I is a bit unfortunate that you need to include easymodbus as *.jar from the \lib directory. I expected that if I exclude slf4j v1 and include slf4j v2 instead, Spring won't have a problem a problem with slf4j v2.

**Comment by jluthiger** [comment]
@ergo-furrer This include is only necessary as long as the library `commhandler4modbus` v1.0.1 s not publicly available in the central maven repo. I haven't setup a local maven repo!

**Review by ArndGerns — APPROVED** [review]

**Comment by ergo-furrer** [comment]
@jluthiger 
I merged your changes now. However before I publish v1.0.1 I would like to do some refactoring since I just realised that the project file structure is not according to Java standards. I will let you know when v1.0.1 is published on our maven repo. 
Is that OK for you?

**Comment by ergo-furrer** [comment]
@jluthiger 
The easymodbus library v1.0.1 is on our maven repository now.
https://nexus.library.smartgridready.ch/#browse/browse:maven-public:ch%2Fsmartgridready%2Feasymodbus%2F1.0.1

**Pull request merged**
